### ISSUE TITLE
Bad OTP setup GtfsFile IDs 

### ISSUE THREAD

**Issue by kpwebb** [opentripplanner/OTPSetup#3]
I just realized that we're using a timestamp to label the uploaded GtfsFiles. Unfortunately this is a risky strategy as there's no guarantee that the time stamps are unique. I just attempted to transload several dozen GTFS files from a server near the AWS server (i.e. very quick transfer times), as a result several of the files ended up with the same names and I assume overwrote the previous entity.  See here:

http://deployer.opentripplanner.org/admin/client/instancerequest/12/

Can we change this so that the names use the id from the GtfsFile object? That's unique and there's no reason not to use it. Also, while we're at it we should go ahead and strip off the original name. It's not useful and may end up causing problems if someone uploads something with an invalid UNIX file name. 

The names should read something like this:

uploads/12/123.zip (where 123 is the GtfsFile id)

**Comment by novalis** [comment]
No, we can't use the id from the GtfsFile object because that object doesn't exist until the upload is complete.  I could replace the data with a UUID -- how does that sound?

I kept the original name for debugging purposes; Amazon alters the filenames to make them unix-safe.  Given this, do you want the filename kept?

**Comment by kpwebb** [comment]
While at it, perhaps it would be smart to make sure that this isn't done anywhere else in the system. Given that its entirely automated we don't want to be overwriting stuff by accident.

**Comment by kpwebb** [comment]
Ah, I see. The object already existed in my case because I was using the transloader, not the file upload. UUID could work but what about creating/saving the object and then using the generated id? seems easier to keep track (and just requires one extra DB call) but either works.

**Comment by novalis** [comment]
OK, I decided to just use uuid; this avoids the risk of having the database go out of sync with s3.

It looks like the only place datestamps are used is in the graph builder, and we don't expect to be building more than one graph per request per second.
