### ISSUE TITLE
Allow users to select fare modules

### ISSUE THREAD

**Issue by kpwebb** [opentripplanner/OTPSetup#4]
Take advantage of custom fare modules by allowing user to select which is used for a specific graph (e.g. NYC, SF, etc.)

**Comment by novalis** [comment]
I pushed a version of this; we need to test it.

**Comment by kpwebb** [comment]
You mean you pushed an OTP plugin, not an update to the setup system, correct?  Let's look at ways to test the plugin and incorporate it into the setup workflow.

kpw

**Comment by kpwebb** [comment]
Oh, i see the commit for setup! Awesome! let's test with NYC
